development: &default
  alg: HS256
  ttl: <%= 1.month %>
  # TODO: change name to application name
  issuer: YOURAPP

test:
  <<: *default

qa:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  ttl: <%= 5.minutes %>
